title: Ryan Jung 
subtitle: Technical Blog
description: >- # this means to ignore newlines until "baseurl:"
  Developers

url: "https://94juho.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about#/
    - text: Contact Me
      url : /contact#/
    

# Edit these details

author_logo: profile.png
author: Ryan Jung
author_bio: This website is Ryan Blog. I am interested in deep learning and reinforcement learning. And I am currently a master's degree in department of software at the Korea National University of Transportation. If you have any questions, please contact me through the contact me menu or send me an email to my email address.   
author_email: "jjs1005k@ut.ac.kr"
author_location: Chungju, Republic of Korea
author_website_url: "https://94juho.github.io"

author_work_experiences:
            - company_name: JICS (2020.08)
              company_logo: jics.png
              company_url: https://doi.org/10.7472/jksii.2020.21.4.109
              designation: Intelligent Railway Detection Algorithm Fusing Image Processing and Deep Learning for the Prevent of Unusual Events(1st author)
              description: Rapid-transit railway, Railway, Deep learning, Fusion
              visibility: true
            - company_name: APIC-IST(Conference, Oral) (05~07.07.2020)
              company_logo: jics.png
              company_url: http://apicist.org/2020/index.html
              designation: Intelligent Abnormal-Event Detection System using Vision, Audio, Dust Sensors(1st author)
              description: Abnormal event, Audio, Dust, Intelligent system, Vision
              visibility: true
            - company_name: MTAP (2020.06) - SCIE
              company_logo: springer.png
              company_url: https://doi.org/10.1007/s11042-020-09149-1
              designation: Real-time unusual user event detection algorithm fusing vision, audio, activity, and dust patterns(1st author)
              description: Intelligence, Vision, Deel learning, Unusual event, Pattern recognition
              visibility: true
            - company_name: ICONI(Conference, Oral) (15~18.12.2019)
              company_logo: iconi.jpg
              company_url: http://www.iconi.org/portal/main.do
              designation: Unusual Indoor Event Detection System using Vision, Audio, and Activity Sensors(1st author)
              description: Activity, Audio, Deep learning, Emergency, Sensors, Vision
              visibility: true
            - company_name: TIIS (2019.11) - SCIE
              company_logo: tiis.png
              company_url: https://doi.org/10.3837/tiis.2019.11.002
              designation: A Review of Intelligent Self-Driving Vehicle Software Research(2nd author)
              description: Self-driving vehicle, Road infrastructure, Deep learning, Machine learning, Localization
              visibility: true 
            - company_name: KSCI (2019.08)
              company_logo: ksci.jpg
              company_url: https://doi.org/10.9708/jksci.2019.24.08.095
              designation: Intelligent Pattern Recognition Algorithms based on Dust, Vision and Activity Sensors for User Unusual Event Detection(2nd author)
              description: Vision, Activity, Dust, Pattern Recognition, Artificial Intelligence
              visibility: true 
            - company_name: APIC-IST(Conference, Poster) (23~26.06.2019)
              company_logo: jics.png
              company_url: http://apicist.org/2019/index.html
              designation: Intelligent Road Traffic Recognition for Precision Maps of Self-driving Cars(1st author)
              description: Self-driving, Cars, Precision Maps, Road Traffic Recognition, Intelligent
              visibility: true
            - company_name: KSCI (2019.05)
              company_logo: ksci.jpg
              company_url: https://doi.org/10.9708/jksci.2019.24.05.059
              designation: Intelligent User Pattern Recognition based on Vision, Audio and Activity for Abnormal Event Detections of Single Households(1st author)
              description: Vision, Audio, Activity, Pattern Recognition
              visibility: true
            - company_name: KSCI (2019.05)
              company_logo: ksci.jpg
              company_url: https://doi.org/10.9708/jksci.2019.24.05.067
              designation: Localization of Mobile Users with the Improved Kalman Filter Algorithm using Smart Traffic Lights in Self-driving Environments(1st author)
              description: Self-driving, Localization, RSSI, Smart traffic lights, Kalman filter
              visibility: true
            - company_name: KISM(Conference, Oral) (26~27.04.2019) *best paper award
              company_logo: ksm.png
              company_url: http://kism.jams.or.kr
              designation: Home Security System based on Intelligent Vision, Audio Pattern Algorithms(2nd author)
              description: Intelligent, Vision, Audio, home security
              visibility: true
            - company_name: KSII Spring Conference (04.2019)
              company_logo: jics.png
              company_url: http://www.ksii.or.kr/
              designation: Health Care System based on Intelligent vision, audio, activity pattern algorithms(2nd author)
              description: 
              visibility: true
            - company_name: JICS (2019.01)
              company_logo: jics.png
              company_url: https://doi.org/10.7472/jksii.2019.20.1.77
              designation: Intelligent Abnormal Event Detection Algorithm for Single Households at Home via Daily Audio and Vision Patterns(1st author)
              description: Vision, Image Processing, Audio, Fusion, Pattern, Daily Behavior, Single Households
              visibility: true
            - company_name: KSII fall Conference (2018.10)
              company_logo: jics.png
              company_url: http://www.ksii.or.kr/
              designation: Health Care Related Noxious Gas Detection System(2nd author)
              description: 
              visibility: true
            - company_name: KSII Spring Conference (2018.04)
              company_logo: jics.png
              company_url: http://www.ksii.or.kr/
              designation: Unusual Event Detection Algorithm via Personalized Video and Voice Patterns for Preventing Solitary Death(1st author)
              description: 
              visibility: true
            - company_name: 저널이름
              company_logo: google.png
              company_url: doi입력
              designation: 논문제목
              description: 키워드
              visibility: false

author_education_details:
              - college_logo: knut.png
                college_name: Korea National University of Transportation
                college_degree: Master's Degree(2019.09~Now)
                description: Department of Software
                visibility: true
              - college_logo: knut.png
                college_name: Korea National University of Transportation
                college_url: https://www.ut.ac.kr
                college_degree: Undergraduate graduation(2013.03~2019.08)
                description: Department of Software
                visibility: true

author_project_details:
              - project_thumbnail: nrf.jpg
                project_title: 건물 재난 현장 3D 영상 객체인식 디지털지도 생성을 위한 스마트폰과 융합한 분산된 보급형 로봇 기반 인공지능 알고리즘 및 SW 개발연구(2020.06~2020.12)
		project_description: Disaster sites, 3D Object detection, A.I, Digital map, Visual SLAM, Deep Learning, Low-cost robot, Smartphone
		project_url: 
                visibility: true
	      - project_thumbnail: kaia.jpg
	        project_title: 철도차량 이상상태 자동검지를 위한 스마트 유지보수 장치개발(2020.04~2020.12)
	        project_description: Railway, Abnormal event, Object detection, OpenCV
	        project_url: 
	        visibility: true
	      - project_thumbnail: lx.jpg
                project_title: 자율주행 차량을 위한 정밀디지털지도 자동생성 기반 알고리즘 개발연구(2018.11~2019.11)
                project_description: Python, Object Detection, Tensorflow, LiDAR, HD Mapping
                project_url: 
                visibility: true
              - project_thumbnail: tipa.jpg
                project_title: 자율주행차 및 횡단보도 사고를 줄이기 위한 차세대 신호등(2018.08~2019.01)
                project_description: BLE, Beacon, RSSI, Android, Kalman Filter
                project_url: 
                visibility: true
              - project_thumbnail: nrf.jpg
                project_title: 스마트시티 CCTV와 스마트폰이 융합한 위험암시 이상징후 탐지연구(2017.03~2020.02)
                project_description: Vision, Activity, Dust, Audio, Pattern Recognition, Object Detection, Unusual Event Detection, Abnormal Event Detection
                project_url: https://github.com/94JuHo
                visibility: true

# social links
github_username: 94JuHo
linkedin_username: ryan-juho-jung-b4074a193
medium_username: jjs1005k
telegram_username: ryanjung

#for comments using disqus
disqus_shortname: ryanblog-2 

# wakatime username (coding activity)
wakatime_username: jjs1005k@naver.com

# formspree (contact form)
formspree_email: jjs1005k@ut.ac.kr

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-147525291-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: WQNWYDD9IL
  index_name: ryanblog # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 20d8f9a51ef78fcf95e6a001f3197ae1

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
